# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atrelease < Formula
  desc "Multi-agent release preparation team for multi-language repositories"
  homepage "https://github.com/plexusone/agent-team-release"
  version "0.8.0"
  license "MIT"

  depends_on "gh"
  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/plexusone/agent-team-release/releases/download/v0.8.0/agent-team-release_0.8.0_darwin_x86_64.tar.gz"
      sha256 "8e03329f73b9002a44e4dc7f743883e48faf2f4fb72e669a984bffb57306da73"

      define_method(:install) do
        bin.install "atrelease"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/plexusone/agent-team-release/releases/download/v0.8.0/agent-team-release_0.8.0_darwin_arm64.tar.gz"
      sha256 "0f87becaca9f9b811627ca4ca73abcad72bea0631d2a75d84de8f07aeb7265af"

      define_method(:install) do
        bin.install "atrelease"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/plexusone/agent-team-release/releases/download/v0.8.0/agent-team-release_0.8.0_linux_x86_64.tar.gz"
      sha256 "9e036d8e0eca6f5656b66adcd30548e018ea36804ae4dd0671a9a10d106cde94"
      define_method(:install) do
        bin.install "atrelease"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/plexusone/agent-team-release/releases/download/v0.8.0/agent-team-release_0.8.0_linux_arm64.tar.gz"
      sha256 "b5fe9955661a2acaef4c2f4edf4fa5477ff3f8174c32ee25c12d61f0b5927958"
      define_method(:install) do
        bin.install "atrelease"
      end
    end
  end

  test do
    system "#{bin}/atrelease", "version"
  end
end
